- name: Set hostnames on all routers via SSH expect
  hosts: localhost
  gather_facts: no

  vars:
    routers:
      - { ip: "172.20.10.6", new_hostname: "R1" }
      - { ip: "172.20.10.7", new_hostname: "R2" }
      - { ip: "172.20.10.8", new_hostname: "R3" }

  tasks:
    - name: Set hostname on {{ item.new_hostname }}
      expect:
        command: ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-rsa -oCiphers=+aes128-cbc cisco@{{ item.ip }}
        responses:
          'Password:': "cisco\n"
          '>': "enable\n"
          'Password:': "cisco\n"
          '#': |
            configure terminal
            hostname {{ item.new_hostname }}
            end
            write memory
            exit
        timeout: 30
        echo: yes
      loop: "{{ routers }}"
