
- name: Configure subinterfaces for VLANs via SSH
  hosts: localhost
  gather_facts: no

  vars:
    router_ip: 172.20.10.8

  tasks:
    - name: Set up subinterfaces for VLAN 10 and 20
      expect:
        command: ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-rsa -oCiphers=+aes128-cbc cisco@{{ router_ip }}
        responses:
          'Password:': "cisco\n"
          '>': "enable\n"
          'Password:': "cisco\n"
          '#': |
            configure terminal
            interface FastEthernet0/1
            no ip address
            no shutdown
            exit
            interface FastEthernet0/1.10
            encapsulation dot1Q 10
            ip address 192.168.50.1 255.255.255.0
            exit
            interface FastEthernet0/1.20
            encapsulation dot1Q 20
            ip address 192.168.60.1 255.255.255.0
            end
            write memory
            exit
        timeout: 30
        echo: yes
